MQTT

diff --git a/build/host-serial-rpi/install-deb-armhf b/build/host-serial-rpi/install-deb-armhf
--- a/build/host-serial-rpi/install-deb-armhf
+++ b/build/host-serial-rpi/install-deb-armhf
@@ -10,7 +10,6 @@ if [ $LEN -ne 32 ]; then
 fi
 
 ARCH=$(dpkg --print-architecture)
-
 echo "Build debian package for $ARCH"
 echo "First make everything."
 
@@ -18,10 +17,22 @@ echo "First make everything."
 make
 
 HERE=`pwd`
-
+ 
+BASE="./debian-${ARCH}"
 DEST="./debian-${ARCH}/usr/local/bin"
 LIBS="./debian-${ARCH}/usr/local/etc"
+DEBS="./debian-${ARCH}/DEBIAN"
 
+./mkControl.sh > ${BASE}/DEBIAN/control
+
+if [ ! -d ${DEBS} ];then
+    mkdir -p ${DEBS}
+fi
+
+if [ ! -f ${DEBS}/control ]; then
+    echo "Fatal Error: No package control file"
+    exit 1
+fi
 
 if [ ! -d ${DEST} ]; then
     mkdir -p ${DEST}
