Added test for control file.

diff --git a/build/host-serial-linux64/install-deb-amd64 b/build/host-serial-linux64/install-deb-amd64
--- a/build/host-serial-linux64/install-deb-amd64
+++ b/build/host-serial-linux64/install-deb-amd64
@@ -20,7 +20,16 @@ HERE=`pwd`
 
 DEST="./debian-${ARCH}/usr/local/bin"
 LIBS="./debian-${ARCH}/usr/local/etc"
+DEBS="./debian-${ARCH}/DEBIAN"
 
+if [ ! -d ${DEBS} ];then
+    mkdir -p ${DEBS}
+fi
+
+if [ ! -f ${DEBS}/control ]; then
+    echo "Fatal Error: No package control file"
+    exit 1
+fi
 
 if [ ! -d ${DEST} ]; then
     mkdir -p ${DEST}
